int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int _checker(int n);
int is_prime_number(int n);
int is_palindrome(char *s);
int wring_it_in(char *s, int n, int k);
int length(char *s);
int check(int x, int n);
int prime_check(int x, int y);
